# Generated by Django 3.1.2 on 2020-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='datEnd',
            field=models.DateTimeField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporting',
            name='datStart',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='idServi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporting',
            name='idTecni',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
