# Generated by Django 3.1.2 on 2020-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportService', '0002_auto_20201007_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='datEnd',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='datStart',
            field=models.DateTimeField(blank=True),
        ),
    ]
